#!/bin/bash
#----------------------------------------------------
# Sample Slurm job script
#   for TACC Stampede2 KNL nodes
#
#   *** Serial Job on Normal Queue ***
# 
# Last revised: 20 Oct 2017
#
# Notes:
#
#   -- Copy/edit this script as desired.  Launch by executing
#      "sbatch knl.serial.slurm" on a Stampede2 login node.
#
#   -- Serial codes run on a single node (upper case N = 1).
#        A serial code ignores the value of lower case n,
#        but slurm needs a plausible value to schedule the job.
#
#   -- For a good way to run multiple serial executables at the
#        same time, execute "module load launcher" followed
#        by "module help launcher".

#----------------------------------------------------

#SBATCH -J cnn           # Job name
#SBATCH -o cnn.o%j       # Name of stdout output file
#SBATCH -e cnn.e%j       # Name of stderr error file
#SBATCH -p gtx          # Queue (partition) name
#SBATCH -N 1               # Total # of nodes (must be 1 for serial)
#SBATCH -n 1               # Total # of mpi tasks (should be 1 for serial)
#SBATCH -t 00:30:00        # Run time (hh:mm:ss)
#SBATCH --mail-user=naiqiao1995@gmail.com
#SBATCH --mail-type=all    # Send email at begin and end of job
#SBATCH -A Cross-Layer-ML-HW       # Allocation name (req'd if you have more than 1)

# Other commands must follow all #SBATCH directives...

module load python3
mkdir -p /home1/07150/ny2639/lab1/CrossLayer_Lab1/output
 

# Launch serial code...
python /home1/07150/ny2639/lab1/CrossLayer_Lab1/cnn7c5fc.py > /home1/07150/ny2639/lab1/CrossLayer_Lab1/output/out7c5fc
#export CUDA_VISIBLE_DEVICES=0
#python /home1/07150/ny2639/lab1/CrossLayer_Lab1/cnn.py > /home1/07150/ny2639/lab1/CrossLayer_Lab1/output/out12c &


#export CUDA_VISIBLE_DEVICES=1
#python /home1/07150/ny2639/lab1/CrossLayer_Lab1/cnn1c11fc.py > /home1/07150/ny2639/lab1/CrossLayer_Lab1/output/out1c11fc &

#export CUDA_VISIBLE_DEVICES=2
#python /home1/07150/ny2639/lab1/CrossLayer_Lab1/cnn18c.py >  /home1/07150/ny2639/lab1/CrossLayer_Lab1/output/out18c &

#export CUDA_VISIBLE_DEVICES=3
#python /home1/07150/ny2639/lab1/CrossLayer_Lab1/cnn1c17fc.py > /home1/07150/ny2639/lab1/CrossLayer_Lab1/output/out1c17fc &

#wait
# ---------------------------------------------------
